---
title: "Ejemplos de graficos de ggplot2 y plotly"
format: html
toc: true
lang: es
theme: yeti
---

# Carca de pauqetes
```{r}
#| Label: Carga-paquetes
#| message: false
#| warning: false

library(DT)
library(plotly)
library(tidyverse)
library(gapminder)
library(ggthemes)
library(hrbrthemes)

```


# Conjunto de datos

## mpg

```{r}
# Tabla de datos de mpg
mpg |>
  select(manufacturer, year, cty, hwy)|>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```


## Diamonts

```{r}
#| label: diamantes
#| message: false
#| warning: false

# Tabla de datos de diamonts
diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```


## Gapminder
```{r}
#| label: gapminder
#| message: false
#| warning: false

# Tabla de datos de gapminder
gapminder |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```


# Ggplot2

```{r}
#| label: ggplot2

ggplot( data = mpg) + geom_point(aes(x = displ, y = hwy))
```



```{r}
#|llabel: ggplo2-2

mpg |>
  ggplot(aes(x = displ, y = hwy)) +
  geom_point()
```



```{r}
#|llabel: ggplo2-3

mpg |>
  ggplot(aes(x = displ, y = hwy, color = class)) +
  geom_point()
```



```{r}
#|llabel: ggplo2-4

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point()
```



```{r}
#|llabel: ggplo2-5


# Gráfico de dispersión de cilindrada vs millas por galón en autopista
# con formas y colores correspondientes al tipo de automóvil
mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point() +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))
```



```{r}
#|llabel: ggplo2-6

# Gráfico de dispersión que muestre la relacion entre el PIB (x) y esperanza de vida (y)
gapminder |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```



```{r}
#|llabel: ggplo2-7

# Gráfico de dispersión que muestre la relacion entre el PIB (x) y esperanza de vida (y), para el año 2007
gapminder |>
  filter(year==2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()+
  geom_smooth(method = "lm")

```



```{r}
#|llabel: ggplo2-8
#|message: false
#|warning: false

# Gráfico de dispersión que muestre la relacion entre el PIB (x) y esperanza de vida (y), para el año 2007
gapminder |>
  filter(year==2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("Relacion entre el PIB per capita y esperanza de vida en 2007")+
  xlab("PIB per capita ($)") +
  ylab("Esperanza de vida") +
  labs(color = "continente") +
  theme_dark()
```







